name: Sync to S3

on:
  push:
    branches:
      - master

env:
  AWS-REGION: ap-southeast-1
  AWS-URL: beta-programming-in-th

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change relative path to absolute path
        run: sed -i -e 's+../media/+https://${AWS-URL}.s3-${AWS-REGION}.amazonaws.com/solutions/media/+g' *
        working-directory: ./md

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${AWS-REGION}

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync . s3://${AWS-URL}/solutions --exclude "*" --include "md/*" --include "media/*" --acl public-read
